server:
  # Port number
  port: 8888

spring:
  thymeleaf:
    mode: LEGACYHTML5 # Allow less rigorous HTML format
    cache: false  # Set false when developing, otherwise it is impossible to see real-time pages
  mvc:
    view:
      prefix: html/
      suffix: .html
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:templates/,classpath:static/
  mail:
    # Configure SMTP server address
    host: smtp.qq.com
    # Sender email address
    username: 342372686@qq.com
    # Configure password (Note: Here is the applied authorization code rather than the real password)
    password: uxepsqpooddscabe
    # Port number is 465 or 587
    port: 587
    # Default email encoding is UTF-8
    default-encoding: UTF-8
    # Configure SSL encryption factory
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # Open the DEBUG mode so that it is convenient to troubleshoot issues as the log of the email sending process will be printed on the console
        debug: true