server:
  # Port number
  port: 8905

  # DataSource Config
spring:
  datasource:
    # 此处使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.114.170.77:3306/rentme?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: rentme
    password: p6LDLcMEZD8e3npM
#    url: jdbc:mysql://localhost:3306/rentme?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
  thymeleaf:
    mode: LEGACYHTML5 # Allow less rigorous HTML format
    cache: false  # Set false when developing, otherwise it is impossible to see real-time pages
  mvc:
    view:
      prefix: html/
      suffix: .html
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:templates/,classpath:static/
  mail:
    # Configure SMTP server address
    host: smtp.qq.com
    # Sender email address
    username: 342372686@qq.com
    # Configure password (Note: Here is the applied authorization code rather than the real password)
    password: uxepsqpooddscabe
    # Port number is 465 or 587
    port: 587
    # Default email encoding is UTF-8
    default-encoding: UTF-8
    # Configure SSL encryption factory
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # Open the DEBUG mode so that it is convenient to troubleshoot issues as the log of the email sending process will be printed on the console
        debug: true

mybatis:
  type-aliases-package: com.example.rentsummary.model
  type-handlers-package: com.example.rentsummary.dao
  mapper-locations: classpath*:mapper/**/*.xml