server:
  #the port number
  port: 8888

spring:
  thymeleaf:
    mode: LEGACYHTML5 #html formal
    cache: false  #Turn off the cache during development, otherwise you will not be able to see the real-time page
  mvc:
    view:
      prefix: html/
      suffix: .html
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:templates/,classpath:static/
  mail:
    # Configure SMTP server address
    host: smtp.qq.com
    # sender email
    username: 342372686@qq.com
    # Configure the password, note that it is not the real password, but the authorization code just applied for
    password: uxepsqpooddscabe
    # port number 465 or 587
    port: 587
    # Default mail encoding is UTF-8
    default-encoding: UTF-8

    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #Indicates that DEBUG mode is turned on, so that the log of the mail sending process will be printed on the console, which is convenient for troubleshooting
        debug: true