server:
  # Port number
  port: 8905

  # DataSource Config
spring:
  datasource:
    # 此处使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.114.170.77:3306/rentme?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: rentme
    password: p6LDLcMEZD8e3npM
  thymeleaf:
    mode: LEGACYHTML5 # Allow less rigorous HTML format
    cache: false  # Set false when developing, otherwise it is impossible to see real-time pages
  mvc:
    view:
      prefix: html/
      suffix: .html
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:templates/,classpath:static/
  mail:
    host: smtp.qq.com
    username: 2057667293@qq.com  # 邮箱地址
    password: ehtnzwqahcoqiahe  # 授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        debug: true
mybatis:
  type-aliases-package: com.example.rentsummary.model
  type-handlers-package: com.example.rentsummary.dao
  mapper-locations: classpath*:mapper/**/*.xml